import { BillingModelPreset } from '@billing/shared';

export const BILLING_MODEL_PRESETS: Record<string, BillingModelPreset> = {
  retail: {
    id: 'retail',
    name: 'Retail & POS Invoicing',
    industry: 'Retail & Commerce',
    description: 'Fast-paced counter and e-commerce invoicing with barcodes/SKU, MRP discounts, and multi-tier GST.',
    defaultTaxSystem: 'GST',
    defaultModules: ['invoices', 'customers', 'products', 'payments', 'reports', 'ai_copilot'],
    suggestedCustomFields: [
      {
        targetEntity: 'invoice',
        fieldName: 'counterId',
        label: 'Checkout Counter / POS Terminal',
        fieldType: 'text',
        required: false,
        order: 1,
      },
      {
        targetEntity: 'product',
        fieldName: 'barcode',
        label: 'Barcode / EAN',
        fieldType: 'text',
        required: false,
        order: 1,
      },
    ],
  },
  subscription: {
    id: 'subscription',
    name: 'SaaS & Recurring Subscriptions',
    industry: 'Technology & Media',
    description: 'Tiered subscription models, proration, automated recurring billing cycles, and seat-based licensing.',
    defaultTaxSystem: 'GST',
    defaultModules: ['invoices', 'customers', 'products', 'payments', 'subscriptions', 'reports', 'ai_copilot'],
    suggestedCustomFields: [
      {
        targetEntity: 'invoice',
        fieldName: 'planCycle',
        label: 'Billing Interval',
        fieldType: 'select',
        options: ['Monthly', 'Quarterly', 'Annual', 'Multi-Year'],
        required: false,
        order: 1,
      },
      {
        targetEntity: 'customer',
        fieldName: 'accountTier',
        label: 'SaaS Tier',
        fieldType: 'select',
        options: ['Starter', 'Growth', 'Enterprise'],
        required: false,
        order: 1,
      },
    ],
  },
  rental: {
    id: 'rental',
    name: 'Rental & Equipment Leasing',
    industry: 'Real Estate & Equipment',
    description: 'Time-based billing, deposits, checkout/check-in tracking, and damage/maintenance surcharges.',
    defaultTaxSystem: 'GST',
    defaultModules: ['invoices', 'customers', 'products', 'payments', 'reports', 'ai_copilot'],
    suggestedCustomFields: [
      {
        targetEntity: 'invoice_item',
        fieldName: 'rentalStartDate',
        label: 'Rental Start Date',
        fieldType: 'date',
        required: true,
        order: 1,
      },
      {
        targetEntity: 'invoice_item',
        fieldName: 'rentalEndDate',
        label: 'Rental End Date',
        fieldType: 'date',
        required: true,
        order: 2,
      },
      {
        targetEntity: 'invoice',
        fieldName: 'securityDeposit',
        label: 'Security Deposit Held (₹)',
        fieldType: 'number',
        required: false,
        order: 3,
      },
    ],
  },
  logistics: {
    id: 'logistics',
    name: 'Logistics & Freight Billing',
    industry: 'Transport & Supply Chain',
    description: 'Weight/distance-based billing, toll surcharge rules, vehicle dispatch metadata, and consignee tracking.',
    defaultTaxSystem: 'GST',
    defaultModules: ['invoices', 'customers', 'products', 'payments', 'reports', 'ai_copilot'],
    suggestedCustomFields: [
      {
        targetEntity: 'invoice',
        fieldName: 'vehicleNumber',
        label: 'Vehicle / Truck Registration',
        fieldType: 'text',
        required: false,
        order: 1,
      },
      {
        targetEntity: 'invoice',
        fieldName: 'docketNumber',
        label: 'Consignment / Docket No.',
        fieldType: 'text',
        required: true,
        order: 2,
      },
      {
        targetEntity: 'invoice_item',
        fieldName: 'weightMetricTon',
        label: 'Weight (MT)',
        fieldType: 'number',
        required: false,
        order: 1,
      },
    ],
  },
  professional_services: {
    id: 'professional_services',
    name: 'Professional Consulting & Agencies',
    industry: 'Legal, Consulting & IT Services',
    description: 'Milestone billing, hourly rate cards, retainer drawdowns, and client project code allocation.',
    defaultTaxSystem: 'GST',
    defaultModules: ['invoices', 'customers', 'products', 'payments', 'reports', 'ai_copilot'],
    suggestedCustomFields: [
      {
        targetEntity: 'invoice',
        fieldName: 'projectCode',
        label: 'Client Project / PO Code',
        fieldType: 'text',
        required: false,
        order: 1,
      },
      {
        targetEntity: 'invoice_item',
        fieldName: 'consultantName',
        label: 'Lead Consultant / Specialist',
        fieldType: 'text',
        required: false,
        order: 1,
      },
    ],
  },
};
